spring:
  application:
    name: Lab1

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 1324
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:liquibase/changelog.yaml
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

feature:
  toggles:
    cosmo-cats: true