openapi: 3.0.0
info:
  title: Category API
  description: API for managing categories in an e-commerce application
  version: 1.0.0
paths:
  /api/v1/categories/{categoryId}:
    get:
      summary: Get a category by its ID
      description: Retrieve a category by its unique identifier.
      operationId: getCategoryById
      parameters:
        - name: categoryId
          in: path
          description: The unique identifier of the category
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Category found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponseDto'
        '404':
          description: Category not found
    delete:
      summary: Delete a category
      description: Remove a category from the system by its ID.
      operationId: deleteCategory
      parameters:
        - name: categoryId
          in: path
          description: The unique identifier of the category to delete
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Category deleted
        '404':
          description: Category not found
    put:
      summary: Update an existing category
      description: Update the details of a category by its ID.
      operationId: updateCategory
      parameters:
        - name: categoryId
          in: path
          description: The unique identifier of the category to update
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryRequestDto'
      responses:
        '200':
          description: Category updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponseDto'
        '400':
          description: Invalid category data
        '404':
          description: Category not found
  /api/v1/categories:
    get:
      summary: Get all categories
      description: Retrieve a list of all categories.
      operationId: getAllCategories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryResponseDto'
    post:
      summary: Add a new category
      description: Create a new category in the system.
      operationId: addCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryRequestDto'
      responses:
        '200':
          description: Category created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResponseDto'
        '400':
          description: Invalid category data

components:
  schemas:
    CategoryRequestDto:
      type: object
      properties:
        name:
          type: string
          description: The name of the category
        description:
          type: string
          description: The description of the category
    CategoryResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The unique identifier of the category
        name:
          type: string
          description: The name of the category
        description:
          type: string
          description: The description of the category
